# Your tumblelog's URL.  Make sure it ends with a /
url: http://tomalared.net/

# The name of your tumblelog
name: TOMALARED.NET
# how many tumbles to show per page?
limit: 30 

# under themes/, what is your tumblelog's directory?
theme: your_tumblelog

# your secret salt, for your cookies
salt: 3t3ttWtiLT$W(t$WTljegW#$g
